config/routes.rb
Rails.application.routes.draw do
 root 'home#homepage'

 resources :users
 resources :cards

  post '/cards/:id/share', to: 'cards#share', as: 'share_card'
  delete '/cards/:id/remove', to: 'cards#remove', as: 'remove_card'

  post '/signin', to: 'sessions#create'
  delete '/signout' => 'sessions#destroy'
  

end

app/models/card.rb
class Card < ActiveRecord::Base

		validates_presence_of :cardnumber, :expmonth, :expyear 

	  validates_numericality_of :expmonth, only_integer: true

	  validates_numericality_of :cardnumber, only_integer: true

	  validates_numericality_of :expyear, only_integer: true

	  validates :cardnumber, length: {in: 15..16}

	  validates :expmonth, inclusion: {in: 1..12, message: " not a valid month. Please enter a 1 or 2 digit month"}, length: {in: 1..2, message: " is not a valid month. Please enter a 1 or 2 digit month"}

	  validates :expyear, length: {is: 4, message: " is not a valid year. Please enter a 4 digit year"}

	  validates_numericality_of :expyear, greater_than_or_equal_to: 2015, :message => " is already expired. Please enter a valid expiration year"
	  validate :valid_card_num

	  has_many :users, through: :user_cards
	  has_many :user_cards

	  before_save :card_type_check

		def card_type_check
		if self.cardnumber.starts_with?("37")
			self.cardtype =  "American Express"
		elsif self.cardnumber.starts_with?("38")
			self.cardtype = "Diners Club"
		elsif self.cardnumber.starts_with?("4")
			self.cardtype = "Visa"
		elsif self.cardnumber.starts_with?("5")
			self.cardtype = "MasterCard"
		elsif self.cardnumber.starts_with?("6")
			self.cardtype = "Discover"
		else
			self.cardtype = "Undefined Travel Card"
		end
	end

	def cardnumber_display
		if self.cardnumber.starts_with?("3")
			self.cardnumber.gsub(/(.{4})(.{6})(?=.)/, '\1 \2 ')
		elsif self.cardnumber.starts_with?("4","5","6")
			self.cardnumber.gsub(/(.{4})(?=.)/, '\1 \2')
		else
			self.cardnumber
		end
	end

	private

	def valid_card_num
		errors.add(:cardnumber, " is not a valid debit card type. Please double-check the card number") unless cardnumber.start_with?('3', '4', '5', '6')
	end


end

app/models/user.rb
class User < ActiveRecord::Base

validates_presence_of :email, :fname, :lname

has_secure_password

validates_presence_of :password, on: :create

validates :email, uniqueness: true

validates :password, length: { minimum: 4 },
confirmation: true

validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message:" format must be xxx-xxx-xxxx"}

has_many :cards, through: :user_cards
has_many :user_cards


def full_name
	if !fname.empty? && !lname.empty?
		fname.capitalize+" "+lname.capitalize
	elsif !fname.empty?
		fname.capitalize
	elsif !lname.empty?
		lname.capitalize
elsif fname.empty? && lname.empty?
  username
	end
end

def has_card?(card_id)
cards = user_cards.collect {|f| f.card_id}
cards.include?(card_id)
end


end

app/models/user_card.rb
class UserCard < ActiveRecord::Base
	belongs_to :user
	belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	session[:id] ? User.find(session[:id]) : nil
  end
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def index
		
	end

	def edit
		@card = Card.find(params[:id])
	end

	def show
		@card = Card.find(params[:id])
	end

	def new
		@card = Card.new
	end

	def create
		@card = Card.new(cardparams.merge(card_owner_id: current_user.id))
		if @card.save
			current_user.cards << @card
			redirect_to user_path(current_user.id)
			flash[:notice] = "Card has been saved!"
		else
			flash[:alert] = "Card was not saved successfully."
			render :new
		end
	end

	def update
		@card = Card.find(params[:id])
		if @card.update(cardparams)
			redirect_to root_path, notice: "Card updated!"
		else
			flash[:alert] = "Card was not udpated."
			render :edit
		end
	end

	def share
		@card = Card.find(params[:id])
		@shared_user = User.find_by(email: params[:email])
		if !@shared_user.has_card?(@card.id)
			@shared_user.cards << @card
			flash[:notice] = "Card shared with #{@shared_user.full_name}."
			render :show
		else
			flash[:alert] = "Cannot complete request. You are already sharing this card with #{@shared_user.full_name}."
			render :show
		end
	end	

	def remove
    	UserCard.where(user_id: current_user.id, card_id: params[:id]).first.destroy
    	redirect_to root_path, notice: "Card removed."
  	end

  	def destroy
    	@card = Card.find(params[:id])  	
   	 	if @card.destroy
	      redirect_to root_path, notice: "Card deleted."
	    else
	      flash[:alert] = "Something went wrong."
	      render :edit
		end
  	end

	private

	def cardparams
		params.require(:card).permit(:cardnumber, :cardtype, :expmonth, :expyear, :balance)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def homepage
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@user = User.find_by(email: params[:email])
		if @user and @user.authenticate(params[:password])
			flash[:notice] = "Successfully logged in!"
			session[:id] = @user.id
		else
			flash[:alert] = "Incorrect login information."
		end
		redirect_to root_path
	end	

	def destroy
		session[:id] = nil
		flash[:notice] = "You have logged out successfully!"
		redirect_to root_path
	end

end

app/controllers/user_cards_controller.rb
class UserCardsController < ApplicationController
  before_action :set_user_card, only: [:show, :edit, :update, :destroy]

  # GET /user_card
  # GET /user_card.json
  def index
    @user_cards = UserCard.all
  end


  def show
  end


  def new
    @user_card = UserCard.new
  end


  def edit
  end


  def create
    @user_card = UserCard.new(user_card_params)

    respond_to do |format|
      if @user_card.save
        format.html { redirect_to @user_card, notice: 'User card was successfully created.' }
        format.json { render :show, status: :created, location: @user_card }
      else
        format.html { render :new }
        format.json { render json: @user_card.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @user_card.update(user_card_params)
        format.html { redirect_to @user_card, notice: 'User card was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_card }
      else
        format.html { render :edit }
        format.json { render json: @user_card.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user_card.destroy
    respond_to do |format|
      format.html { redirect_to user_cards_url, notice: 'Users card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_user_card
      @user_card = UserCard.find(params[:id])
    end

   
    def user_card_params
      params.require(:user_card).permit(:user_id, :card_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
    	@total_balance = @user.cards.sum(:balance) 
	end
 
	def edit
		@user = User.find(params[:id])
	end

  def update
    @user = User.find(params[:id])
  	if @user.update(user_params)
    	redirect_to @user, notice: "User successfully updated."
    else
      flash[:alert] = "Something went wrong."
      render :edit
    end
 end

	def new
		@user = User.new
	end

	def create
		@user = User.new(userparams)
		if @user.save
			session[:id] = @user.id
			redirect_to @user, notice: "User created!"
		else
			flash[:alert] = "User was not created successfully."
			render :new
		end			
	end


	def destroy
		if session[:id] == @user.id
			session[:id] = nil
			# @user = User.find(params[:id]).destroy
			@user.destroy
			redirect_to users_path, notice: "User deleted!"
		else
			redirect_to users_path, notice: "User was not deleted."
		end
	end

	private

	def userparams
		params.require(:user).permit(:email, :password, :password_confirmation, :fname, :lname, :phone)
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper

# LOOK AT THE USERS CONTROLLER. User.id is now being set to something called session[:id], which we use for this action to create a user session.

  # if session[:id]
  # 	User.find(session[:id])
  # else
  # 	nil
  # end

  def current_user
  	session[:id] ? User.find(session[:id]) : nil
  end

  def shared_name(card_owner_id)
  	User.find(card_owner_id).full_name
  end



end

app/views/cards/_form.html.erb
<%= form_for @card do |d| %>
	
	<%= d.label :cardnumber, "Card Number" %>
    <%= d.text_field :cardnumber, :required => true, placeholder: "xxxxxxxxxxxxxxxx" %>
    <br />
    <br />
    <%= d.label :expmonth, "Expiration Month" %>
    <%= d.number_field :expmonth, :required => true, placeholder: "xx" %> 
    <br />
    <br />
    <%= d.label :expyear, "Expiration Year" %>
    <%= d.number_field :expyear, :required => true, placeholder: "xxxx" %> 
    <br />
    <br />
    <%= d.label :balance, "Balance" %>
    <%= d.number_field :balance, :step => 'any', placeholder: "xxx.xx" %> 
    <br />
    <br />
    <%= d.submit %>

    <% end %>
</div>
  

app/views/cards/edit.html.erb
<%= link_to 'back to home', root_path %>
<% if current_user and current_user.id.to_i == @card.users.first.id.to_i %>
	<h1>Edit or Add Funds to Card</h1>
	<% if @card.errors.full_messages.any? %>
		<ul>
			<% @card.errors.full_messages.each do |error_msg| %>
				<li><%= error_msg %></li>
			<% end %>
		</ul>
	<% end %>
	<%= render 'form' %>
	<br />
	Delete card: 
	<%= link_to 'delete', card_path(@card.id), method: :delete, data: {confirm: "Are you sure you want to delete this card?"} %>
	<br />
<% else %>
	<h1>You must be an admin to view this page!</h1>
<% end %>

app/views/cards/index.html.erb
<h3>Debit Index Page!</h3>

app/views/cards/new.html.erb
<%= link_to 'back', user_path(current_user.id) %>
<br />
<h1>Add a card</h1>
<br />
<h3>All fields are required.</h3>
<% if @card.errors.full_messages.any? %>
	<ul>
		<% @card.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>
<%= render 'form' %>
<br />

app/views/cards/show.html.erb
<%= link_to 'back to MyWallet', user_path(current_user.id) %>
<br />
<h2><%= @card.cardtype %></h2>
<h3>Card Number: <%= @card.cardnumber_display %></h3>
<h3>Expires: <%= @card.expmonth %>/<%= @card.expyear %></h3>
<h2>Balance: <% if !@card.balance.nil? %>
                                <%= number_to_currency(@card.balance, unit: "$") %>
                            <% else %>
                                $0.00
                            <% end %></h2>
<br />

<% if @card.card_owner_id == current_user.id %>
    <h3>Share this card with another user by entering the user's email here:</h3>
    <%= form_tag(share_card_path(@card.id), method: :post) do %>
        <%= label_tag :email, "Email to share card to:" %>
        <%= text_field_tag :email, nil, {placeholder: "Another user's email..."} %>
        <%= submit_tag "Share" %>
    <% end %>
<% end %>

app/views/home/homepage.html.erb
<% if current_user %>
	<p>
	Hello <%= current_user.fname %> | 
	<%= link_to 'MyWallet', user_path(current_user.id) %>
		| 
	<%= link_to 'Profile Settings', edit_user_path(current_user.id) %>
		| 
	<%= link_to 'Sign Out', signout_path, method: :delete %></p>
<% else %>
	<p><%= form_tag(signin_path, method: :post) do %>
		<%= label_tag :email %>
		<%= text_field_tag :email %>
		<%= label_tag :password %>
		<%= password_field_tag :password %>
		<%= submit_tag "Sign In" %> | 
		<%= link_to 'Sign Up', new_user_path %>
	<% end %></p>
<% end %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Mywallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<div id="flash">
			<%= flash[:notice] if flash[:notice] %>
		</div>

		<div id="alert">
			<%= flash[:alert] if flash[:alert] %>
		</div>

		<div id="container">
			<header>
				<div id="title">
				<% if current_user %>
					<%= current_user.fname %>
				<% else %>
					Hello Guest!
				<% end %>
					<h3>Wallet App</h3>
				</div>

			</header>

			<div id="content">
				<%= yield %>
			</div>

		</div>
	</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |n| %>

    <%= n.label :fname, "First Name" %>
    <%= n.text_field :fname, :required => true %>
    <br />
    <br />
    <%= n.label :lname, "Last Name" %>
    <%= n.text_field :lname, :required => true %> 
    <br />
    <br />
    <%= n.label :email, "Email" %>
    <%= n.text_field :email, :required => true %> 
    <br />
    <br />
    <%= n.label :password, "Password" %>
    <%= n.password_field :password, :required => true %> 
    <br />
    <br />
    <%= n.label :password_confirmation, "Password Confirmation" %>
    <%= n.password_field :password_confirmation, :required => true %> 
    <br />
    <br />
    <%= n.label :phone, "Phone" %>
    <%= n.text_field :phone, placeholder: "xxx-xxx-xxxx" %>
    <br />
    <br />
    <%= n.submit %>

    <% end %>
</div>
  

app/views/users/edit.html.erb
<%= link_to 'back to home', root_path %>
<% if current_user and current_user.id.to_i == params[:id].to_i %>
	<h1>Edit User</h1>
	<% if @user.errors.full_messages.any? %>
		<ul>
			<% @user.errors.full_messages.each do |error_msg| %>
				<li><%= error_msg %></li>
			<% end %>
		</ul>
	<% end %>
	<%= render 'form' %>
	<br />
	Deactivate your account: 
	<%= link_to 'delete', user_path(current_user.id), method: :delete, data: {confirm: "Warning: This action cannot be undone. Are you sure?"} %>
	<br />
<% else %>
	<h1>You must be an admin to view this page!</h1>
<% end %>

app/views/users/index.html.erb
<h3> User Index Page! </h3>
<ul><% @users.each do |user| %>
		<li>
			<%= link_to user.fname+" "+user.lname, user_path(user) %>

			<%= link_to user.email, user_path(user) %>

			<%= link_to "edit", edit_user_path(user) %>

			<%= link_to "delete", user_path(user.id), method: :delete %>
		</li>

	<% end %>
</ul>

<%= link_to "Create user", new_user_path %>

app/views/users/new.html.erb
<h3> Create a New User! </h3>

<%= render 'form' %>
<br />
<%= link_to 'cancel', users_path %>

app/views/users/show.html.erb
<%= link_to 'back to home', root_path %>
<br />
<h1><%= @user.fname %>, here's what's inside of YourWallet:</h1>
<br />
<h2>Total Balance: <strong><%= number_to_currency(@total_balance, unit: "$") %></strong></h2>
<br />
<%= link_to 'Add a card', new_card_path %>
<br />
<h2>Cards in YourWallet: </h2>
<% if @user.cards.first.nil? %>
	You haven't added any cards yet. To add a card, click the link above.
<% else %>
	<ul>
		<% @user.cards.each do |card| %>
			<li><%= card.cardtype %>: <%= link_to card.cardnumber_display, card_path(card.id) %> | Card Balance: 
				<strong><% if !card.balance.nil? %>
					<%= number_to_currency(card.balance, unit: "$") %>
				<% else %>
					$0.00
				<% end %></strong> - 
				<% if current_user && card.card_owner_id == current_user.id %>
					<%= link_to 'share', card_path(card.id) %> | <%= link_to 'edit or add funds', edit_card_path(card.id) %> | <%= link_to 'delete', card_path(card.id), method: :delete, data: {confirm: "Are you sure you want to delete this card?"} %>
				<% else %>
					Shared card from <%= shared_name(card.card_owner_id) %> -
					<%= link_to 'remove card', remove_card_path(card.id), method: :delete, data: {confirm: "Are you sure you want to remove this #{card.card_type} shared with you?"} %>
				<% end %></li>
		<% end %>
	</ul>
<% end %>